### ISSUE TITLE
Loading page during upload is very poor due to colour overlay

### ISSUE THREAD

**Issue by Teky500** [Teky500/Ebook-PR-Application#21]
![Screenshot_2024-03-09_182736](https://github.com/Teky500/Ebook-PR-Application/assets/24497097/a9532526-72b2-42b4-89c3-bc31c7efb929)

Picture above for reference. Look into either colouring and size or border changes (or something different) to fix the overlay issue.

**Comment by fostoq** [comment]
Fixed issue.

**Comment by fostoq** [comment]
closing issue.
