### ISSUE TITLE
app crashes when no network connection

### ISSUE THREAD

**Issue by joshuarugema** [Teky500/Ebook-PR-Application#30]
app crashes when updating with no internet connection. Probably needs a check for connection status code prior to attempting to check for updates. We would want to show a pop up to user to connect to a network instead of crashing the app when not connected.

**Comment by Teky500** [comment]
I have added the backend functionality to check for this, and it currently behaves correctly while outputting to the terminal. Need @fostoq to make some frontend portion (such as something that says "Could not fetch data from CRKN" or something).

**Comment by Teky500** [comment]
@joshuarugema this should be fixed now, please double check and reopen if it doesn't work.
