### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by joshuarugema** [Teky500/Ebook-PR-Application#32]
When there's no internet connection and the app is reset or started the starting page stays on endlessly.(might just be awaiting the frontend update of no internet connection)

**Comment by Teky500** [comment]
This is awating the frontend update, but also we need to decide on what to do if there is no internet and the application is starting for the first time.. Does it proceed with an empty database?

**Comment by Jitterynull** [comment]
I think It should prompt a "Please check internet connection and try again" message then close itself

**Comment by Teky500** [comment]
This is fixed now, @joshuarugema please double check and reopen if it doesnt work on the latest dev branch.
