### ISSUE TITLE
Include error handling for when url provided has no excel files

### ISSUE THREAD

**Issue by joshuarugema** [Teky500/Ebook-PR-Application#34]
Basically if the link provided to the config file upon initial launch does not have any excel files user should be prompted to check the link as no excel files were found with the url provided

**Comment by Teky500** [comment]
How should this be handeled?

**Comment by Teky500** [comment]
Should be fixed on the latest dev branch, the page messages are a bit wonky but the functionality should be there. Reopen if issue rearises or does not pass test.
