### ISSUE TITLE
OCN and eISBN search crashes application

### ISSUE THREAD

**Issue by joshuarugema** [Teky500/Ebook-PR-Application#36]
I attempted to search using OCN and eISBN and it kept crashing with an sqlite error. inputs tried (9780203499474, and 9780203499474*)
<<
Traceback (most recent call last):
  File "/Users/mucyojoshua/Desktop/Ebook-PR-Application/source/features/searchPageDriver.py", line 188, in search
    s_result = search_ISBN(text, 'source/storage/database/proj.db')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mucyojoshua/Desktop/Ebook-PR-Application/source/features/helpers/search.py", line 22, in search_ISBN
    cursor.execute(f"SELECT books.*, platforms.platform  FROM BOOKS JOIN PLATFORMS ON Books.spreadsheet  = platforms.spreadsheet; where ISBN = '{ISBN}'")
sqlite3.ProgrammingError: You can only execute one statement at a time.

>>

**Comment by fostoq** [comment]
Removed semi colin in SQL query. Fixed now, closing issue.

**Comment by fostoq** [comment]
Hello @joshuarugema, if you wouldn't mind testing this again once the branch has been integrated into dev!

Thank you
