### ISSUE TITLE
Change update finished message to be more accurate?

### ISSUE THREAD

**Issue by Jitterynull** [Teky500/Ebook-PR-Application#40]
When you finish an update it prompts the user with "data **already** updated. But it was not already done previously.

**Comment by Teky500** [comment]
Are you on an outdated branch? This is already correct on my end.

**Comment by Jitterynull** [comment]
For some reason it's only an issue in french, I'm looking into it.

**Comment by Jitterynull** [comment]
Found and fixed issue.
