### ISSUE TITLE
Second correct excel file breaks program on upload

### ISSUE THREAD

**Issue by Jitterynull** [Teky500/Ebook-PR-Application#47]
I am in an up to date dev branch, when I upload the second correct excel file I get the following error and the application crashes/closes.

Traceback (most recent call last):
  File "c:\Users\evanl\.vscode\Ebook-PR-Application\source\features\UploadPage.py", line 154, in handle_upload_result
    self.upload_success = UploadSuccess(f'{result[1]} lignes ajoutΘes avex succΦs!')
                                           ~~~~~~^^^
IndexError: list index out of range
PS C:\Users\evanl\.vscode\Ebook-PR-Application> 

Not sure if this is just an issue on my end or application wide.

**Comment by Teky500** [comment]
Should be fixed, I broke something when making the error messages more human readable.
