### ISSUE TITLE
Application crashes on occasion drawing getLanguage error

### ISSUE THREAD

**Issue by fostoq** [Teky500/Ebook-PR-Application#57]
Mohab to fill with fix

**Comment by fostoq** [comment]
The animated text was calling getLanguage every time it was changing the text, so that was called continously. Seems like that carries over even after starting the homepage and what not. Not 100% sure about what goes next but, if you manipulate the config at the wrong time (using yaml.dump for example), and the getlanguage gets called, it sees an empty config bc it is being manipulated

**Comment by Teky500** [comment]
Animation was calling getLanguage continously, and continued past the starting page, so manipulating the config file at the wrong time led to this error. Fixed by ending the animation when the starting page is done, and removing the continous getLanguage checks.
