### ISSUE TITLE
Keyboard interrupt is being caught and stopping application from force closing

### ISSUE THREAD

**Issue by joshuarugema** [Teky500/Ebook-PR-Application#71]
Error closing application

**Comment by Teky500** [comment]
Fixed: the excepthook now does a sys.exit() call when the error type is a KeyboardInterrupt. It seems like the QApplication event loop doesn't pick this up though, the user needs to interact with the application somehow for the call to happen. Worked around by having a constant QTimer event every second that does nothing, but it allows the KeyboardInterrupt error to get caught and proceed as usual to force close.
